# Generated by Django 5.0.2 on 2024-02-17 18:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Apellido')),
                ('phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='Telefono')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='Direccion')),
                ('date_joined', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Ingreso')),
                ('last_joined', models.DateField(default=django.utils.timezone.now, verbose_name='Ultimo Ingreso')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='¿Administrador?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.CharField(blank=True, choices=[('truck', 'Camion'), ('car', 'Carro'), ('motobyke', 'Moto')], max_length=256, verbose_name='Vehiculo')),
                ('license', models.CharField(blank=True, max_length=256, unique=True, verbose_name='Placa')),
            ],
            options={
                'verbose_name': 'Transportista',
                'verbose_name_plural': 'Transportistas',
            },
            bases=('user.account',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company', models.CharField(blank=True, max_length=256, verbose_name='Empresa')),
                ('nit', models.CharField(blank=True, max_length=256, verbose_name='NIT/RUT')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=('user.account',),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['username'], name='user_accoun_usernam_65cfe6_idx'),
        ),
    ]
