# Generated by Django 5.0.2 on 2024-02-17 15:36

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('weight', models.FloatField(help_text='Peso (kg)', verbose_name='Peso')),
                ('height', models.FloatField(help_text='Altura (cm)', verbose_name='Altura')),
                ('width', models.FloatField(help_text='Ancho (cm)', verbose_name='Ancho')),
                ('depth', models.FloatField(help_text='Largo (cm)', verbose_name='Largo')),
                ('source', models.CharField(max_length=256, verbose_name='Origen')),
                ('address', models.CharField(max_length=256, verbose_name='Direccion')),
                ('state', models.CharField(blank=True, choices=[('hold', 'Pendiente'), ('delivered', 'Entregado'), ('refused', 'Devuelto')], max_length=256, verbose_name='¿Estado?')),
                ('date_joined', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso')),
                ('date_delivery', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Entrega')),
                ('is_paid', models.BooleanField(default=False, verbose_name='¿Pagado?')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
