# Generated by Django 5.0.2 on 2024-02-17 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.carrier'),
        ),
        migrations.AddField(
            model_name='package',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.client'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['id', 'carrier', 'client'], name='logistics_p_id_c8a0fa_idx'),
        ),
    ]
