# Generated by Django 5.0.2 on 2024-02-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_package_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='¿Pagado?'),
        ),
    ]
